spring.application.name=POST-SERVICE


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=test



eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUU3ByaW5nQm9vdDM=
