spring.application.name=POST-SERVICE

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
server.port=8085
spring.datasource.password=12345678
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=test



eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUU3ByaW5nQm9vdDM=

# Cloudinary Configuration
cloudinary.cloud-name=oopoispw
cloudinary.api-key=178819685665431
cloudinary.api-secret=hJYBFClHln_nDV7KTsBp2-3Rbhc
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB