server:
  port: 9090


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: AUTH-SERVICE
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/a/**
            filters:
                - StripPrefix=1

          - id: POST-SERVICE
            uri: lb://POST-SERVICE
            predicates:
              - Path=/p/**
            filters:
              - StripPrefix=1
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
                - Path=/user/**
            filters:
              - StripPrefix=1

management.endpoints.web.exposure.include: '*'

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
